# Generated by Django 4.2.4 on 2023-09-17 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_noti", "0003_message_receiver_alter_chat_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
    ]
