# Generated by Django 4.2.4 on 2023-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="post",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="base.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pictures",
            field=models.ImageField(blank=True, upload_to="images/photos"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="images/profile_pics/"),
        ),
    ]
