# Generated by Django 4.2.4 on 2023-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_message_groupmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="follow",
        ),
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="base.profile"
            ),
        ),
    ]
