# Generated by Django 4.2.4 on 2023-08-30 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_post_follow_profile_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
